steps:
  #コンテナイメージをビルドする
  - name: "gcr.io/cloud-builders/docker"
    args: ['build', '-t=asia-northeast2-docker.pkg.dev/$PROJECT_ID/harumax-container-image/static-site', '--build-arg=JEKYLL_ENV=$_JEKYLL_ENV', '.']
  #コンテナイメージをpushする
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia-northeast2-docker.pkg.dev/$PROJECT_ID/harumax-container-image/static-site"]
  #もろもろの設定
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "alpha"
      - "run"
      - "deploy"
      - "static-site"
      - "--image=gcr.io/$PROJECT_ID/static-site"
      - "--region=asia-northeast1"
      - "--platform=managed"
      - "--allow-unauthenticated"
