steps:
  #コンテナイメージをビルドする
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/static-site", "."]
  #コンテナイメージをpushする
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/static-site"]
  #もろもろの設定
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "alpha"
      - "run"
      - "deploy"
      - "static-site"
      - "--image=gcr.io/$PROJECT_ID/static-site"
      - "--region=asia-northeast1"
      - "--platform=managed"
      - "--allow-unauthenticated"
